// Demo data: about a year of programs, sessions and runs, generated by running the real
// progression rules week by week. Loaded from the welcome screen or (on localhost) the backup sheet.
import * as L from './logic.js';
import { blank } from './store.js';

const DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];

// name, sets, min, max, starting kg, weekly jump
const EX = {
  'Leg press': [4, 10, 15, 110, 5],
  'Bulgarian split squat': [3, 8, 12, 14, 2],
  'Leg extension': [4, 12, 15, 40, 2.5],
  'Calf raise': [3, 12, 20, 50, 2.5],
  'Hack squat': [3, 8, 12, 60, 5],
  'Shoulder press': [3, 8, 12, 16, 2],
  'Machine fly': [4, 10, 15, 30, 2.5],
  'V pull down': [4, 10, 12, 45, 2.5],
  'Tricep bar': [3, 10, 15, 20, 2.5],
  'Bicep curls': [3, 10, 15, 10, 1],
  'Back rows': [4, 8, 12, 40, 2.5],
  'Shoulder flys': [3, 12, 20, 6, 1],
  'Chest press': [3, 8, 12, 40, 2.5],
  'Hamstring curls': [4, 10, 15, 35, 2.5],
  'SLDL': [3, 8, 12, 50, 2.5],
  'Abductor': [3, 12, 20, 40, 2.5],
  'Pendulum squat': [3, 10, 15, 40, 5],
  'Leg press (wide/high)': [3, 10, 15, 100, 5],
  'Hip thrust': [3, 8, 12, 60, 5],
  'Tricep pushdown': [3, 10, 15, 25, 2.5],
  'Hammer curls': [3, 8, 12, 12, 1],
};

const W = {
  quads: ['Quads', ['Leg press', 'Bulgarian split squat', 'Leg extension', 'Calf raise']],
  quadsOld: ['Quads', ['Hack squat', 'Leg press', 'Leg extension', 'Calf raise']],
  upperA: ['Upper A', ['Shoulder press', 'Machine fly', 'V pull down', 'Tricep bar', 'Bicep curls']],
  upperB: ['Upper B', ['Back rows', 'Chest press', 'Shoulder flys', 'Tricep pushdown', 'Hammer curls']],
  hams: ['Hamstrings', ['Hamstring curls', 'SLDL', 'Abductor', 'Calf raise']],
  glutes: ['Glutes', ['Pendulum squat', 'Leg press (wide/high)', 'Hip thrust', 'Abductor']],
};

// weeksAgo = how many Mondays back the program started; plan: day -> [workoutKey, runType]
const PROGRAMS = [
  { name: 'Winter 2025', weeksAgo: 53, weeks: 16, plan: { mon: ['quadsOld'], tue: ['upperA'], wed: ['hams', 'threshold'], thu: ['upperB'], sat: [null, 'long'] } },
  { name: 'Spring 2026', weeksAgo: 35, weeks: 14, plan: { mon: ['quads'], tue: ['upperA'], wed: ['hams', 'threshold'], thu: ['upperB', 'easy'], fri: ['glutes'], sat: [null, 'long'] } },
  { name: 'Summer 2026', weeksAgo: 20, weeks: 14, plan: { mon: ['quads'], tue: ['upperA'], wed: ['hams', 'threshold'], thu: ['upperB', 'easy'], fri: ['glutes'], sat: [null, 'long'] } },
  { name: 'Autumn 2026', weeksAgo: 4, weeks: 12, plan: { mon: ['quads'], tue: ['upperA'], wed: ['hams', 'threshold'], thu: ['upperB', 'easy'], fri: ['glutes'], sat: [null, 'long'] } },
];

// Small seeded random so the demo looks the same every time.
function rng(seed) {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) % 4294967296;
    return s / 4294967296;
  };
}

export function buildDemo() {
  const S = blank();
  const rand = rng(42);
  const todayIso = L.isoDate();
  const thisMonday = L.addDays(todayIso, -((new Date().getDay() + 6) % 7));
  const idOf = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  let n = 0;
  const id = (p) => `${p}${(n++).toString(36)}`;

  for (const [name, [, , , kg, step]] of Object.entries(EX)) {
    S.exercises[idOf(name)] = { id: idOf(name), name, step };
    S.targets[idOf(name)] = { weight: kg, reps: EX[name][1], miss: 0 };
  }

  let runWeek = 0;
  PROGRAMS.forEach((pd, pi) => {
    const start = L.addDays(thisMonday, -7 * pd.weeksAgo);
    const current = pi === PROGRAMS.length - 1;
    const workouts = {}, days = {}, wid = {};
    for (const [day, [wk, run]] of Object.entries(pd.plan)) {
      const d = {};
      if (wk) {
        if (!wid[wk]) {
          const [wname, exs] = W[wk];
          wid[wk] = id('w');
          workouts[wid[wk]] = { id: wid[wk], name: wname, items: exs.map((e) => ({ exId: idOf(e), sets: EX[e][0], min: EX[e][1], max: EX[e][2] })) };
        }
        d.workout = wid[wk];
      }
      if (run) d.run = run;
      days[day] = d;
    }
    const prog = {
      id: id('p'), name: pd.name, weeks: pd.weeks, startDate: start,
      endDate: current ? null : L.addDays(start, pd.weeks * 7 - 1), archived: !current, days, workouts,
    };
    S.programs.push(prog);
    if (current) S.currentId = prog.id;

    for (let w = 0; w < pd.weeks; w++) {
      runWeek++;
      for (const [day, d] of Object.entries(days)) {
        const date = L.addDays(start, 7 * w + DAYS.indexOf(day));
        if (date >= todayIso) continue;

        if (d.workout && rand() > 0.06) {
          const wo = workouts[d.workout];
          const entries = wo.items.map((it) => {
            const ex = S.exercises[it.exId];
            const tRaw = S.targets[it.exId];
            const t = { weight: tRaw.weight, reps: L.clamp(tRaw.reps, it.min, it.max) };
            const sets = [];
            for (let i = 0; i < it.sets; i++) {
              const r = rand();
              const failChance = 0.03 + i * 0.04; // later sets fail more often
              let reps = t.reps;
              if (r < failChance) reps = Math.max(1, t.reps - (rand() < 0.7 ? 1 : 2));
              else if (r > 0.96) reps = t.reps + 1;
              sets.push({ reps, weight: t.weight, hit: reps >= t.reps });
            }
            const nx = L.nextTarget({ sets: it.sets, min: it.min, max: it.max }, ex.step, t, sets, tRaw.miss || 0);
            S.targets[it.exId] = { weight: nx.weight, reps: nx.reps, miss: nx.miss };
            return { exId: it.exId, cfg: { sets: it.sets, min: it.min, max: it.max }, target: t, sets };
          });
          S.sessions.push({ id: id('s'), date, programId: prog.id, workoutId: wo.id, workoutName: wo.name, minutes: 45 + Math.round(rand() * 25), entries });
        }

        if (d.run && rand() > 0.08) {
          const noise = (rand() - 0.5) * 12; // ± 6 s/km
          let distKm, pace;
          if (d.run === 'threshold') {
            distKm = Math.min(8, 5 + Math.floor(runWeek / 12) * 0.5);
            pace = 325 - runWeek * 0.55 + noise;
          } else if (d.run === 'long') {
            const build = runWeek % 4 === 0 ? -2 : 0; // every 4th week is a lighter one
            distKm = Math.min(21, 10 + runWeek * 0.18 + build);
            pace = 370 - runWeek * 0.3 + noise;
          } else {
            distKm = 5 + Math.round(rand() * 10) / 10;
            pace = 372 - runWeek * 0.2 + noise;
          }
          distKm = Math.round(distKm * 10) / 10;
          S.runs.push({ id: id('r'), date, programId: prog.id, type: d.run, distKm, timeSec: Math.round(distKm * pace) });
        }
      }
    }
  });

  S.sessions.sort((a, b) => a.date.localeCompare(b.date));
  S.runs.sort((a, b) => a.date.localeCompare(b.date));
  S.demo = true;
  return S;
}
